### ISSUE TITLE
Detachable header lagging

### ISSUE THREAD

**Issue by daviddeutsch** [marcobarbosa/minima#13]
Had this a couple of times and am not sure to what extend you can control this, but the detachable header can get rather sticky to the point where it's apparently eating up my CPU.

**Comment by daviddeutsch** [comment]
(this is in FF3.6 btw)

**Comment by marcobarbosa** [comment]
Hmm that doesn't sound good nor something I could fix :(

Can you try in a different browser and let me know if this happens?

**Comment by daviddeutsch** [comment]
Tried it in the latest chrome and it works, so I guess it's mostly due to JS performance.

One thing I noticed though that in Chrome, the detachable header is always spawned from the top right, not just from the top like in FF.

**Comment by marcobarbosa** [comment]
That is true. I'll leave this open for a while to see if I can fix this "top right" thing later.

Thanks!

**Comment by marcobarbosa** [comment]
transition padding only, closed by 1ec4faf7d063d0a17567ed762d8589b112c005ae
