### ISSUE TITLE
Extension Manager Install - Button Upload and Install

### ISSUE THREAD

**Issue by danielcorrea** [marcobarbosa/minima#15]
Marco,

veja o erro na imagem 
Firefox 3.6.10 - http://ow.ly/i/8r8l
Chrome 8 - http://ow.ly/i/8r8Q 

Creio que o correto seja o exibido pelo Opera 10 - http://ow.ly/i/8r91

**Comment by marcobarbosa** [comment]
fixed in the latest minima

**Comment by danielcorrea** [comment]
yep
