### ISSUE TITLE
Template Edit Screen is missing "view site"

### ISSUE THREAD

**Issue by betweenbrain** [marcobarbosa/minima#16]
With templates that have some sort of back-end configuration, it is very handy to be able to save changes and view a site preview, without closing the edit screen.

 I'd suggest evaluating adding the "view site" link on screens that make changes to the front end and that also have a save (a.k.a apply) function.

**Comment by marcobarbosa** [comment]
That could work..

How can I detect that I'm in a template edit screen, so I can add the "view site" link?

**Comment by betweenbrain** [comment]
That's a good question. Maybe the quick fix is to add the view site link to all views that have the Minima logo.

**Comment by marcobarbosa** [comment]
I see what you mean. I'm adding that.

Thanks!

**Comment by marcobarbosa** [comment]
added site-link to edit view, closed by a7d06f22b33677c0c25b6c07550ef01b19e33c25

**Comment by betweenbrain** [comment]
Cool, thanks!
