### ISSUE TITLE
Components Area Completely Blank

### ISSUE THREAD

**Issue by ethode** [marcobarbosa/minima#17]
Love the theme!  However, after installing and click the top header link for components, the resulting drop down area was empty.. I read through wiki and docs is there a step I missed?

Thanks, love this thing!

**Comment by marcobarbosa** [comment]
Hi there! Thanks for the kind words :)

No you didn't miss a step, looks like something went wrong during the install.

What you can try is:
- Go to the module manager (top right of the header, click the tools icon then "modules")
- Look for "mypanel", that's the name of the panel module
- Make sure it's published. Even if it is published, just click "Save & Close" to make sure you're telling Joomla "this is here"

Let me know how it goes..

**Comment by marcobarbosa** [comment]
Closing this issue.

Please let me know again if you're still having trouble. Thanks!
