### ISSUE TITLE
3rd party components do not appear correctly in components panel

### ISSUE THREAD

**Issue by michaw** [marcobarbosa/minima#22]
It looks like the language files are not being read correctly or something similar. For example:
Joomla Content Editor (JCE) appears as:

jce
JCE_XML_DESCRIPTION

**Comment by danielcorrea** [comment]
The same problem occurs with Ck Editor

**Comment by marcobarbosa** [comment]
Guys, update to latest minima (download the latest version and install over it to update) and let me know if the problem remains, please.

Daniel, could you send me a link for me to download Ck Editor?

**Comment by danielcorrea** [comment]
Oi Marco,

segue o link - http://joomlacode.org/gf/project/ckeditor/frs/?action=index

**Comment by marcobarbosa** [comment]
Daniel,

Você tem razão, o CK Editor não usa o "padrão"

---

You guys are correct, there seems to be no patterm among JCE and CkEditor..

So I can't "guess" it what string they're using for the description.

Will look more into this later.

**Comment by marcobarbosa** [comment]
Added "No description available" message to work around this for now.
