### ISSUE TITLE
error in cpanel.php and raphael.js

### ISSUE THREAD

**Issue by ghazal** [marcobarbosa/minima#28]
Hi,
great admin template, very functional.
But I think there is a small path error to raphael.js in cpanel.php (typo ?) in my version (0.8)
Around line 62 :
   <script>!window.Raphael && document.write(unescape('%3Cscript src="templates/<?php echo $this->template ?>/js/raphael.min.js"%3E%3C/script%3E'))</script>    

should be :
   <script>!window.Raphael && document.write(unescape('%3Cscript src="templates/<?php echo $this->template ?>/js/raphael/raphael.min.js"%3E%3C/script%3E'))</script>    

Please bear with me if you already corrected it.
BTW, I love raphael.js too.

Cheers
Ghazal

**Comment by marcobarbosa** [comment]
Nice! will fix it!

Would you like to help on minima with some raphael.js things?

I'm looking for some raphaeljs enthusiasts. Let me know if you are interested :)

**Comment by ghazal** [comment]
Hi,
I am not very savvy with raphael.js
I am just playing/experimenting with its implementation in Mootools,
like this, an old forge plugin (by sixtyseconds: https://github.com/sixtyseconds, not even distributed anymore) that I modified a little bit to work with Moo 1.3
http://ghazalp.fr/MOOTOOLS/RAPHAEL/example.html

I don't know if I will be of much help.
