### ISSUE TITLE
Components drop down does not work in Chrome.

### ISSUE THREAD

**Issue by vikingv** [marcobarbosa/minima#30]
The minima template's Components drop down box does not respond and no components can be accessed when using Google Chrome.  I have the latest Joomla 1.64 & Chrome 12.0742.112 

It works great in Firefox and IExplorer.

**Comment by marcobarbosa** [comment]
Hey vikingv!

Can you post a screenshot if possible?

Sounds weird that it works in Firefox and IExplorer. 

I will try with the Joomla and Chrome version you mentioned and get back to you about this.

**Comment by Nebrit** [comment]
access to the management of articles with google chrome and you can see how the parameters and permissions tabs do not go.

**Comment by marcobarbosa** [comment]
Do you have any JS error?

I'm trying in the demo and I can see the tabs working:
http://demo.minimatemplate.com/administrator/index.php?option=com_content&view=article&layout=edit&id=1

**Comment by marcobarbosa** [comment]
Nebrit, I just tested in 1.7 and I can't replicate this issue so I'm closing it.

Feel free to re-open with a screenshot or more information if this problem happens to you again.

Thanks.
