### ISSUE TITLE
Navigation doesn´t shows

### ISSUE THREAD

**Issue by gate0keeper** [marcobarbosa/minima#31]
Hello guys,

I just found minima and loved / installed it, but the main navigation buttons doesn´t show up.
I have tested with different browsers and Joomla systems: 1.63v2 and 1.64.

Could you give me a hit to the right direction?

Cheers,
Daniel

**Comment by marcobarbosa** [comment]
Could you attach a screenshot?

Have you got any Javascript errors ? (do you know how to check it?)

**Comment by gate0keeper** [comment]
Hello,

thanks for the really fast reply.
No, I don´t get any errors showing up, I am using firebug:
http://http://altstadthotel-am-theater.de/error.jpg

The: nav id=shortcut" ??? /nav also is empty :(

**Comment by marcobarbosa** [comment]
Looks like you are missing mod_myshortcuts.

Go to your module manager (index.php?option=com_modules) and see if it's there published in the position "shortcuts" 
or go to com_installer and see if it's installed at all.

Edit: After you found out what's missing, I'd also like to know how you installed minima so we can find out the reason for this. Thanks!

**Comment by gate0keeper** [comment]
I guess this would be the problem. I can´t see that module, even in ftp view. 
Can you eventually tell me were to find the module?

I just installed the very new Joomla 1.64 and have noticed that I don´t like the admin layout, so I searched a better one. I am out of date with joomla a long time because of time issues, but the requirements of that actual project are joomla + some modules.

**Comment by gate0keeper** [comment]
Sorry, I just downloaded the complate package, so I could intsall the my_shortcuts an the panel module.
The navigation is running now, only I have problems left with the dashboard, as it shows up empty. :(:(

**Comment by marcobarbosa** [comment]
Something went wrong during your install.

All you have to do now is:

1) go to the module manager
2) select "Admin" (to show the administrator modules) in the filter 
3) assign the modules (latest_news etc) to "widgets-first" and "widgets-last"

**Comment by gate0keeper** [comment]
thanks a lot, is working now like a charm
