### ISSUE TITLE
mypanel fixes

### ISSUE THREAD

**Issue by mbabker** [marcobarbosa/minima#32]
Using latest Minima, I've made the following tweaks to improve mod_mypanel display:

1) Define $class as "", this is done in case an extension comes after an extension which has an $img which does not exist to prevent later extensions from being forcibly rendered with the generic icon.  Below code extends current conditional in mod_mypanel/tmpl/default.php:

// fallback if img not found
if (!file_exists($img)) {
    $class = "icon-48-generic";
} else {
    $class = "";
}

2) The current class definition causes 3PD extensions to not be rendered with icon padding.  Below definition replaces existing in css/template.css:
# panel-list li.ext img {

float: left;
padding-left: 32px;
padding-right: 12px;
padding-top: 12px;
}

Tested against Firefox 5.0 and Chrome 12.0.742.112

**Comment by marcobarbosa** [comment]
Thanks Michael! Added those changes.

I like it how you take care of mypanel :)

The changes are both in the dashboard branch (it will be merged soon) and mypanel repo.
