### ISSUE TITLE
Bug in translation Spanish

### ISSUE THREAD

**Issue by Nebrit** [marcobarbosa/minima#33]
Spanish translation, the accents are not displayed correctly and get a symbol.

Joomla 1.6.5 / minimatemplate ultimate version.

Thanks

jna@lexnos.com

**Comment by marcobarbosa** [comment]
Thanks for your email Nebrit.

Looks like the strings got messed up during transfer. Don't know how to avoid this.

I'm including the fixed version in the next commit. And that will be included in the next release.

Thanks again!
