### ISSUE TITLE
Only first page of components showing

### ISSUE THREAD

**Issue by ghost** [marcobarbosa/minima#37]
Hi

First of all; great template, thank you.

I have an issue with the components panel. The first slide of components shows up with no problems but when I click the arrow and go to the second page nothing shows up, it's just a blank space.

I have tested this on more than one Joomla site (all 1.7) and in Firefox, Chrome and Safari on my Mac Pro. I also have the newest version of Minima installed (downloaded today).

Thanks

**Comment by marcobarbosa** [comment]
Hi designsubway,

It seems there is an issue with the pagination calculation.
The calculation returns as there are two pages but there is only one.

You will probably get one extra blank page always for now  :)

So you can ignore that blank page..this will be fixed soon.

**Comment by marcobarbosa** [comment]
designsubway, looks like this issue is related to this one https://github.com/marcobarbosa/minima/issues/38

I will let you know for more information soon.

I'm closing this one because it's a duplicate.
