### ISSUE TITLE
Components pull down only working on Home or Configuration pages

### ISSUE THREAD

**Issue by itsmedrew2** [marcobarbosa/minima#38]
I have the latest build of Joomla 1.7.  I LOVE the minima template, but I am having some issues with it.  The components pull down ONLY works when I have clicked on the home icon or i'm in the configuration area.  Every other area it does not respond.  Also, any time I add a new component it of course pushes component icons to an additions page, I receive the arrow to go to the next page and I get to the next page, however, there is nothing there.  So, currently I am also unable to access a few of my components.  Any suggestions?

**Comment by marcobarbosa** [comment]
Hi istmedrew2,

To be honest I havent tested Minima on Joomla 1.7 yet.

It looks have a javascript conflict or error going on. 

Do you have any JS errors in your console?

**Comment by itsmedrew2** [comment]
I'm not seeing any errors.  Is there something I should be doing to check for errors?

Sincerely,

Andrew Etner
Web/Graphic Designer & Joomla Specialist
(574)383-9462
www.aideacomm.us

**Comment by marcobarbosa** [comment]
What browser are you on?

For Chrome just go to Tools > "Javascript Console"

For Internet Explorer hit F12 and click "Console""

Just make sure it's minima/joomla related stuff. You can clear the console and refresh the page for that.

**Comment by itsmedrew2** [comment]
As default I use safari, but I can use anything except IE since I'm on MAC

Sincerely,

Andrew Etner
Web/Graphic Designer & Joomla Specialist
(574)383-9462
www.aideacomm.us

**Comment by itsmedrew2** [comment]
Here's what I'm seeing in the Javascript Console:

Resource interpreted as Stylesheet but transferred with MIME type text/html.                 templates/minima/css/ipad.css:-1
templates/minima/fonts/nobile.woff:-1Resource interpreted as Font but transferred with MIME type application/octet-stream.
ipad.cssFailed to load resource: the server responded with a status of 404 (Not Found)

Sincerely,

Andrew Etner
Web/Graphic Designer & Joomla Specialist
(574)383-9462
www.aideacomm.us

**Comment by marcobarbosa** [comment]
Hmmm no errors :(

(the ipad.css error is already fixed and not related)

I'll have to ask you to wait a little bit. I'll make some 1.7 tests in the next few days.

**Comment by itsmedrew2** [comment]
Ok, no problem! :)

Sincerely,

Andrew Etner
Web/Graphic Designer & Joomla Specialist
(574)383-9462
www.aideacomm.us

**Comment by itsmedrew2** [comment]
Also, just to let you know, sometime save and close buttons are not available when making edits within components.

Sincerely,

Andrew Etner
Web/Graphic Designer & Joomla Specialist
(574)383-9462
www.aideacomm.us

**Comment by marcobarbosa** [comment]
Hi Andrew,

I'm testing a updated version of Minima with 1.7 and I still can't replicate this issue you mentioned. 

Note that you tried with the 1.6 package before (not sure if that would matter though if you installed successfully). 

However this concerns me, so I'm sending you an email from your website and if you're willing to test more I'll email you the new 1.7 package.

You're welcome to re-open this issue in case the components panel is still not working properly then.

Thanks.

**Comment by itsmedrew2** [comment]
Yeah that would be great. I love the minima template and would absolutely love to use it. 

Sincerely,

Andrew Etner

-sent from my iPod
