### ISSUE TITLE
administrator login and complete back end giving server error 

### ISSUE THREAD

**Issue by arc99** [marcobarbosa/minima#40]
Need help urgently. mistakenly i have uploaded this admin template on joomla 1.5 installation directly on my live website. 
the template was installed successfully but when i set is as default something went wrong. since then it is not showing anything on admin panel not even admin login page.

though the websites front-end is working properly and i have access of ftp. so can anything be done from there??

any help will be much appreciated

**Comment by marcobarbosa** [comment]
Hi there,

 Don't worry. You just need access to the database and we can fix this. 

Do you have phpMyAdmin installed ? 

Bluestork just needs to be set as default again.

If you have phpMyAdmin, look for the table that sets the template as default and change it:

Look for the table 'jos_templates_menu', make sure the template that has 1 as client_id is khepri:

template: khepri 
menuid: 0
client_id: 1

You must have only one admin template there as client_id 1 

## 

@MarcoBarbosa
http://marcobarbosa.com

**Comment by arc99** [comment]
Thanks a lot.
I did as you guided and it worked perfectly
