### ISSUE TITLE
Painel dos componentes

### ISSUE THREAD

**Issue by kyllaz** [marcobarbosa/minima#42]
Marco bom trabalho aqui desenvolvido :)
Estou com uma dificuldade que é a seguinte, no painel de componentes em cima só me aparecem 9 componentes, a 2ª página aparece em branco, e quando desactivo um componente o icon já aparece no lugar do que desactivei. Mas pronto isso é o menos. No que eu precisava mesmo de uma dica era como dar permissões aos componentes para aparecerem só num tipo de grupo ou então mesmo desactivar o painel deslizante pois criei todos os acessos para os componente na homepage da administração e acabo por não usar o painel. Se me puderes então dizer como remover o painel ficarei muito agradecido.

Valeu.

**Comment by marcobarbosa** [comment]
Olá kyllaz!

O painel eh um modulo, logo basta despublica-lo :)

Alias por ser um modulo acho que ali mesmo voce seta as permissoes por grupo, nao eh mesmo?

Caso voce nao ache:
- Clique em "Extensoes > Modulos"
- Clique na aba "Admin"
- Procure por "My Panel" (ou mod_mypanel) e despublique

**Comment by kyllaz** [comment]
Obrigado Marco. Valeu:)
Não tinha reparado que o painel era um modulo.

**Comment by marcobarbosa** [comment]
kyllaz,

Acho que você deletou a última mensagem?

EDIT: Posta uma screenshot.

**Comment by marcobarbosa** [comment]
kyllaz,

Fecharei esse issue pois preciso de mais instrucoes do que voce deseja.

Qualquer coisa so re-abrir.
