### ISSUE TITLE
Feature request - Disable component icons and move to menu

### ISSUE THREAD

**Issue by Oceanwatcher** [marcobarbosa/minima#45]
I am an information junkie - I admit it!

One thing that is annoying with the Joomla backend is all the space wasted by the quick icons. I prefer to have everything accessible through the menu. The dashboard is best used for information.

Another thing that is a problem is that the menu is not easy to edit. I would prefer that the admin menu could be edited much the same way as the front end menu. What about giving us the possibility to add icons etc. in the admin menu just as the Fusion menu that RocketTheme uses with their templates?

**Comment by marcobarbosa** [comment]
So happy to read this comment, you really got the point of minima :)

The first paragraph you pretty much describe why quick icons are disabled by default and why I focused on improving the menu.

The second paragraph you describe one of the core goals of minima that is the ability to make the menu customisable. 

Unfortunately that is not a straight forward task :( 

First I wanted to be able to do that just with the module but I can't, I have to build a component for it (just for the AJAX CRUD tasks). I also can't re-use the existing "com_menus" for the back-end without hacking things.
And that's where things get complicated (plus the lack of time). 

I don't want minima to become a distro and pack with components and modules just for the sake of fixing J! limitations, you know? The goal is to be minimal and I need to be careful with that.

So it's something I have to study carefully. Meanwhile other things get prioritized and get released before this.

But just so you know that that was the plan in the first place and it's still under consideration.

Thanks for the feedback!

**Comment by marcobarbosa** [comment]
Oceanwatcher, I'm closing this issue just for organization purposes but I totally hear you man.

We actually started something that you could follow here: 
https://github.com/marcobarbosa/com_mymenus

I really want to make that menu editable in a nice UI but we also have other important issues to fix.

Thanks a lot for the feedback!

**Comment by Oceanwatcher** [comment]
You are welcome! Sorry to ask a question after it is closed, but it follows the above:

Is there a way to disable to drop-down panel altogether? Just avoid the possibility to have any icons?

Looking forward to be able to be able to edit the menu easily!

**Comment by marcobarbosa** [comment]
Yeah the panel is a module so just unpublish it :)

Look for "mod_mypanel" and disable it.
