### ISSUE TITLE
Feature Request - Action button at top and bottom

### ISSUE THREAD

**Issue by jsanglier** [marcobarbosa/minima#47]
One of the weaknesses of the core Joomla! templates is that the New, Save and other buttons are only at the top. Where you have a long list in the article manager, or the component options form goes on forever, this is a complete pain.

Any chance of duplicating the buttons on the bottom too? Maybe bottom left for Western users who tend to read left to right? (possibly the other side for R-L language variants!)

**Comment by marcobarbosa** [comment]
Hi jsanglier,

What about the sticky header as you scroll down? 

That should help too and that was the intention of it..

I'm afraid the bottom would have too much because of the "batch" tasks. But it's not a bad idea :)

**Comment by jsanglier** [comment]
Ah, hadn't seen that on the article list. (only have one article in my test!)

What about on components and articles though? Some components especially can have mighty long forms by the time you have put in map info, name of dogs best friend and the rest. And if you are doing a multi-page article, that can get long too.

The list of permissions has made all that worse in some cases - though you have helped that by putting them in a tab, which is good.

**Comment by jsanglier** [comment]
Oops - closed by accident!

**Comment by marcobarbosa** [comment]
The sticky header should be enabled on components and articles as well. 

I haven't found a long component to test it but if you try in editing a module for example, you'll notice that it sticks as well.

So I'll close this issue because we have the sticky header for now. Let me know if it's not working properly though.

Thanks!
