### ISSUE TITLE
no new component listed

### ISSUE THREAD

**Issue by ghofweber** [marcobarbosa/minima#49]
after installing a new component e.g. NoNumber
the just installed component is not showing up in the component area

JomVersion 1.7.2
NoNumber Extension Manager 2.6.2

after getting back to default admin template everything is visible

**Comment by marcobarbosa** [comment]
Hmmm that's weird, I'll investigate it soon..

**Comment by ghofweber** [comment]
FYI - after switching back to minima the component is visible again
