### ISSUE TITLE
Php Warnings with Manager/Admin Account

### ISSUE THREAD

**Issue by antoineschaller** [marcobarbosa/minima#51]
Hi!
I tried to install Joomla with this amazing template today (which btw is amazing, congrats!) but got an error when i try to access the admin cp with a manager or administrator account. can't figure if i did smthg wrong or if the template's just gone crazy.
Since they are just warnings i could eventually hide them i suppose but i guess it would just hide the problem.

I made a print screen of how it look like : http://screencast.com/t/OKAuj62yckFg

Thanks for everything and sorry for my poor English

**Comment by marcobarbosa** [comment]
Hi quicky67,

Sorry for the late reply.

It could be just Joomla! related warnings. Are you running PHP with the setting E_ALL?

Try running with bluestork and let me know if the warnings remain.

**Comment by antoineschaller** [comment]
hey!

No i'm not running with E_ALL setting, and Bluestorck doesn't display any error when logged which the manager account (or any other)... weird, i surely did something wrong with my config
i use php 5.3 btw

**Comment by marcobarbosa** [comment]
Can you try re-installing the template?
