### ISSUE TITLE
Can't founded *.css files

### ISSUE THREAD

**Issue by themt** [marcobarbosa/minima#52]
if click on "settings" in any administrator page like "content manager" then openning a lightbox but its content is broken and console of browser said follows error:

/administrator/templates/minima/css/libs/template.reset.css 404 (Not Found)
/administrator/templates/minima/css/libs/template.forms.css 404 (Not Found)
/administrator/templates/minima/css/libs/template.buttons.css 404 (Not Found)
/administrator/templates/minima/css/libs/template.icons.css 404 (Not Found)

And thank you for this template, it's good!

**Comment by marcobarbosa** [comment]
Hi the-mt,

How did you install the template? From the .zip or did you clone from the repository?

Those CSS files should be only in the repository like a "development" mode.

Actually why do you have /administrator in the front :O

See here to know what I mean:
https://github.com/marcobarbosa/minima/blob/master/administrator/templates/minima/index.php#L49-55

Can you clarify how you installed it?

**Comment by themt** [comment]
i did download template from "http://minimatemplate.com/download/" addres, download url is "http://minimatemplate.com/get/pkg_minima.zip"

i did install *.zip file in install page of extension manager in backend.

i see error if i click any "settings" button in backend (administrator side)

Screenshot > http://imageshack.us/photo/my-images/838/missingcssfiles.jpg/

**Comment by marcobarbosa** [comment]
Aw shit I know what it is..

Thanks a lot for reporting this.

If you want a fix just change "component.php" and in the < head > you remove those CSS files.
Copy the css link from "index.php" and paste it there.

It should be only "template.min.css".

To be more clear:

```
<link href="templates/<?php echo $this->template ?>/css/libs/template.reset.css" rel="stylesheet">
<link href="templates/<?php echo $this->template ?>/css/libs/template.buttons.css" rel="stylesheet">
<link href="templates/<?php echo $this->template ?>/css/libs/template.forms.css" rel="stylesheet">
<link href="templates/<?php echo $this->template ?>/css/libs/template.icons.css" rel="stylesheet">
<link href="templates/<?php echo  $this->template ?>/css/template.css" rel="stylesheet" />
```

To:

```
<link href="templates/<?php echo  $this->template ?>/css/template.min.css" rel="stylesheet" />
```

That should do it.

**Comment by themt** [comment]
Yes! it's working

Thank you, i love this template!

**Comment by marcobarbosa** [comment]
Thanks man!

Still lots of work to be done though :)

I'll leave this issue open until I commit a fix.

Thanks again!
