### ISSUE TITLE
One-click's Find Updates producing errors.

### ISSUE THREAD

**Issue by Duke3D** [marcobarbosa/minima#57]
One click update is pointing to Minimatemplate.com/update/modules/... URLs that do not resolve and instead produce errors in Extension Manager - Update - Find Updates.  Would it be better to delist from one-click until URLs are stable?  (Ignore if already solved, I will be pulling a fresh copy.)

**Comment by marcobarbosa** [comment]
Agreed. I can disable this until I get the update sorted out. 

Not really sure yet how to use this feature..
